version: 2
references:

  default_config: &default_config
    docker:
      - image: gcr.io/bavard-infra/devops:1.0.0
        auth:
          username: _json_key  # default username when using a JSON key file to authenticate
          password: $GOOGLE_CREDENTIALS  # JSON service account you created

  version-tags-only: &version-tags-only
    # Filter that only matches when there's a git tag representing
    # a package version.
    tags:
      only: /[0-9]+(\.[0-9]+)*/
    branches:
      ignore: /.*/

jobs:

  test:
    <<: *default_config
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: test
          command: scripts/lint-and-test-package.sh

  publish:
    <<: *default_config
    steps:
      - checkout
      - run:
          name: publish
          command: ./scripts/publish.sh

  publish-docs:
    <<: *default_config
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: publish-docs
          command: ./scripts/deploy_docs.sh $FIREBASE_TOKEN

workflows:
  version: 2
  test-and-publish:
    jobs:
      - test:
          context: bavard
          filters:
            tags:
              # Run on all branches, tag or no tag.
              only: /.*/
      - publish:
          context: bavard
          requires:
            - test
          filters:
            # Only publish to pypi when there's a git tag representing
            # a package version.
            <<: *version-tags-only
      - publish-docs:
          context: bavard
          requires:
            - publish
          filters:
            <<: *version-tags-only