version: 2
references:
  default_config: &default_config
    docker:
      - image: gcr.io/bavard-infra/devops:1.0.0
        auth:
          username: _json_key  # default username when using a JSON key file to authenticate
          password: $GOOGLE_CREDENTIALS  # JSON service account you created

  test: &test
    <<: *default_config
    steps:
      - checkout
      - run:
          name: test
          command: scripts/lint-and-test-service.sh
  publish: &publish
    <<: *default_config
    steps:
      - checkout
      - run:
          name: publish
          command: |
            set -eo pipefail
            pip3 install setuptools wheel twine
            python3 setup.py verify
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
            ./scripts/publish.sh

jobs:
  test:
    <<: *test
  publish:
    <<: *publish
workflows:
  version: 2
  test-and-publish:
    jobs:
      - test:
          context: bavard
          filters:
            tags:
              only: /.*/
      - publish:
          context: bavard
          requires:
            - test
          filters:
            # Only publish to pypi when there's a git tag representing
            # a package version.
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
